-d C:\Users\pckle\OneDrive\Desktop\pong\impl\gwsynthesis\hdmi.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\pckle\OneDrive\Desktop\pong\src\hdmi.cst
-cfg C:\Users\pckle\OneDrive\Desktop\pong\impl\pnr\device.cfg
-sdc C:\Users\pckle\OneDrive\Desktop\pong\src\hdmi.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
